export const players = [
  { id: 'ace', name: 'Ace', image: '/assets/players/ace.jpg' },
  { id: 'aizawa', name: 'Aizawa', image: '/assets/players/aizawa.webp' },
  { id: 'allmight', name: 'All Might', image: '/assets/players/allmight.jpg' },
  { id: 'bakugo', name: 'Bakugo', image: '/assets/players/bakugo.webp' },
  { id: 'deku', name: 'Deku', image: '/assets/players/deku.webp' },
  { id: 'gohan', name: 'Gohan', image: '/assets/players/gohan.avif' },
  { id: 'goku', name: 'Goku', image: '/assets/players/goku.avif' },
  { id: 'inosuke', name: 'Inosuke', image: '/assets/players/inosuke.webp' },
  { id: 'itachi', name: 'Itachi', image: '/assets/players/itachi.webp' },
  { id: 'kakashi', name: 'Kakashi', image: '/assets/players/kakashi.webp' },
  { id: 'luffy', name: 'Luffy', image: '/assets/players/luffy.jpeg' },
  { id: 'naruto', name: 'Naruto', image: '/assets/players/naruto.jpg' },
  { id: 'nezuko', name: 'Nezuko', image: '/assets/players/nezuko.webp' },
  { id: 'picolo', name: 'Piccolo', image: '/assets/players/picolo.jpg' },
  { id: 'rengoku', name: 'Rengoku', image: '/assets/players/rengoku.webp' },
  { id: 'rocklee', name: 'Rock Lee', image: '/assets/players/rocklee.webp' },
  { id: 'sanji', name: 'Sanji', image: '/assets/players/sanji.webp' },
  { id: 'sasuke', name: 'Sasuke', image: '/assets/players/sasuke.webp' },
  { id: 'shanks', name: 'Shanks', image: '/assets/players/shanks.webp' },
  { id: 'tanjiro', name: 'Tanjiro', image: '/assets/players/tanjiro.jpg' },
  { id: 'todoroki', name: 'Todoroki', image: '/assets/players/todoroki.png' },
  { id: 'trunks', name: 'Trunks', image: '/assets/players/trunks.webp' },
  { id: 'vegeta', name: 'Vegeta', image: '/assets/players/vegeta.jpg' },
  { id: 'zenitsu', name: 'Zenitsu', image: '/assets/players/zenitsu.jpg' },
  { id: 'zoro', name: 'Zoro', image: '/assets/players/zoro.jpg' },
];
