// src/utils/players_hayAlgoAhi.js

export const hayAlgoAhiPlayers = [
  { id: 'alien',             name: 'Alien',            image: '/assets/players/hayalgoahi/alien.webp' },
  { id: 'bane',              name: 'Bane',             image: '/assets/players/hayalgoahi/bane.webp' },
  { id: 'blanka',            name: 'Blanka',           image: '/assets/players/hayalgoahi/blanka.webp' },
  { id: 'cyrax',             name: 'Cyrax',            image: '/assets/players/hayalgoahi/cyrax.webp' },
  { id: 'darthmaul',         name: 'Darth Maul',       image: '/assets/players/hayalgoahi/darthmaul.webp' },
  { id: 'deadpool',          name: 'Deadpool',         image: '/assets/players/hayalgoahi/deadpool.webp' },
  { id: 'dhalsim',           name: 'Dhalsim',          image: '/assets/players/hayalgoahi/dhalsim.webp' },
  { id: 'generalgrievous',   name: 'General Grievous', image: '/assets/players/hayalgoahi/generalgrievous.webp' },
  { id: 'goro',              name: 'Goro',             image: '/assets/players/hayalgoahi/goro.webp' },
  { id: 'glossurabban',      name: 'Glossu Rabban',    image: '/assets/players/hayalgoahi/glossurabban.webp' },
  { id: 'hansolo',           name: 'Han Solo',         image: '/assets/players/hayalgoahi/hansolo.webp' },
  { id: 'hulk',              name: 'Hulk',             image: '/assets/players/hayalgoahi/hulk.webp' },
  { id: 'inmortanjoe',       name: 'Inmortan Joe',     image: '/assets/players/hayalgoahi/inmortanjoe.webp' },
  { id: 'jax',               name: 'Jax',              image: '/assets/players/hayalgoahi/jax.webp' },
  { id: 'jamesgordon',       name: 'James Gordon',     image: '/assets/players/hayalgoahi/jamesgordon.webp' },
  { id: 'lexluthor',         name: 'Lex Luthor',       image: '/assets/players/hayalgoahi/lexluthor.webp' },
  { id: 'liukang',           name: 'Liu Kang',         image: '/assets/players/hayalgoahi/liukang.webp' },
  { id: 'magneto',           name: 'Magneto',          image: '/assets/players/hayalgoahi/magneto.webp' },
  { id: 'piccolo',           name: 'Piccolo',          image: '/assets/players/hayalgoahi/piccolo.webp' },
  { id: 'predator',          name: 'Predator',         image: '/assets/players/hayalgoahi/predator.webp' },
  { id: 'rasalghul',         name: "Ra's al Ghul",     image: '/assets/players/hayalgoahi/rasalghul.webp' },
  { id: 'silversurfer',      name: 'Silver Surfer',    image: '/assets/players/hayalgoahi/silversurfer.webp' },
  { id: 'terminator',        name: 'Terminator',       image: '/assets/players/hayalgoahi/terminator.webp' },
  { id: 'tarzan',            name: 'Tarzan',           image: '/assets/players/hayalgoahi/tarzan.webp' },
  { id: 'thanos',            name: 'Thanos',           image: '/assets/players/hayalgoahi/thanos.webp' },
  { id: 'thor',              name: 'Thor',             image: '/assets/players/hayalgoahi/thor.webp' },
  { id: 'zangief',           name: 'Zangief',          image: '/assets/players/hayalgoahi/zangief.webp' },
  { id: 'goku',              name: 'Goku',             image: '/assets/players/hayalgoahi/goku.webp' },
];
