// src/utils/players.js

export const players = [
  { id: 'ace',      name: 'Ace',      image: '/assets/players/shonen/ace.jpg' },
  { id: 'aizawa',   name: 'Aizawa',   image: '/assets/players/shonen/aizawa.webp' },
  { id: 'allmight', name: 'All Might',image: '/assets/players/shonen/allmight.jpg' },
  { id: 'bakugo',   name: 'Bakugo',   image: '/assets/players/shonen/bakugo.webp' },
  { id: 'deku',     name: 'Deku',     image: '/assets/players/shonen/deku.webp' },
  { id: 'gohan',    name: 'Gohan',    image: '/assets/players/shonen/gohan.avif' },
  { id: 'goku',     name: 'Goku',     image: '/assets/players/shonen/goku.avif' },
  { id: 'inosuke',  name: 'Inosuke',  image: '/assets/players/shonen/inosuke.webp' },
  { id: 'itachi',   name: 'Itachi',   image: '/assets/players/shonen/itachi.webp' },
  { id: 'kakashi',  name: 'Kakashi',  image: '/assets/players/shonen/kakashi.webp' },
  { id: 'luffy',    name: 'Luffy',    image: '/assets/players/shonen/luffy.jpeg' },
  { id: 'naruto',   name: 'Naruto',   image: '/assets/players/shonen/naruto.jpg' },
  { id: 'nezuko',   name: 'Nezuko',   image: '/assets/players/shonen/nezuko.webp' },
  { id: 'picolo',   name: 'Piccolo',  image: '/assets/players/shonen/picolo.jpg' },
  { id: 'rengoku',  name: 'Rengoku',  image: '/assets/players/shonen/rengoku.webp' },
  { id: 'rocklee',  name: 'Rock Lee', image: '/assets/players/shonen/rocklee.webp' },
  { id: 'sanji',    name: 'Sanji',    image: '/assets/players/shonen/sanji.webp' },
  { id: 'sasuke',   name: 'Sasuke',   image: '/assets/players/shonen/sasuke.webp' },
  { id: 'shanks',   name: 'Shanks',   image: '/assets/players/shonen/shanks.webp' },
  { id: 'tanjiro',  name: 'Tanjiro',  image: '/assets/players/shonen/tanjiro.jpg' },
  { id: 'todoroki', name: 'Todoroki', image: '/assets/players/shonen/todoroki.png' },
  { id: 'trunks',   name: 'Trunks',   image: '/assets/players/shonen/trunks.webp' },
  { id: 'vegeta',   name: 'Vegeta',   image: '/assets/players/shonen/vegeta.jpg' },
  { id: 'zenitsu',  name: 'Zenitsu',  image: '/assets/players/shonen/zenitsu.jpg' },
  { id: 'zoro',     name: 'Zoro',     image: '/assets/players/shonen/zoro.jpg' },
];
